name: vacanza
description: Tubes APB

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.5+3
  path_provider: ^2.0.11

  cupertino_icons: ^1.0.2
  lottie: ^1.3.0
  firebase_core: ^1.18.0
  firebase_database: ^9.0.16
  firebase_auth: ^3.3.20
  form_field_validator: ^1.1.0
  google_maps_flutter: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/poppins/Poppins-Regular.ttf
          weight: 400
        - asset : assets/font/poppins/Poppins-Medium.ttf
          weight : 500
